services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    ports:
      - "49372:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - regtest_pgdata:/var/lib/postgresql/data

  bitcoind:
    image: btcpayserver/bitcoin:29.1
    restart: unless-stopped
    environment:
      BITCOIN_NETWORK: regtest
      BITCOIN_WALLETDIR: "/data/wallets"
      BITCOIN_EXTRA_ARGS: |-
        rpcuser=ceiwHEbqWI83
        rpcpassword=DwubwWsoo3
        rpcport=53782
        rpcbind=0.0.0.0:53782
        rpcallowip=0.0.0.0/0
        port=49388
        whitelist=0.0.0.0/0
        zmqpubrawblock=tcp://0.0.0.0:28332
        zmqpubrawtx=tcp://0.0.0.0:28333
        fallbackfee=0.0002
    ports:
      - "53782:53782"
      - "49388:49388"
    volumes:
      - regtest_bitcoin:/data

  nbxplorer:
    image: nicolasdorier/nbxplorer:2.5.29
    restart: unless-stopped
    ports:
      - "42838:42838"
    environment:
      NBXPLORER_NETWORK: regtest
      NBXPLORER_CHAINS: "btc"
      NBXPLORER_BTCRPCURL: http://bitcoind:53782/
      NBXPLORER_BTCNODEENDPOINT: bitcoind:49388
      NBXPLORER_BTCRPCUSER: ceiwHEbqWI83
      NBXPLORER_BTCRPCPASSWORD: DwubwWsoo3
      NBXPLORER_BIND: 0.0.0.0:42838
      NBXPLORER_MINGAPSIZE: 5
      NBXPLORER_MAXGAPSIZE: 10
      NBXPLORER_VERBOSE: 1
      NBXPLORER_POSTGRES: User ID=postgres;Include Error Detail=true;Host=postgres;Port=5432;Database=nbxplorer
      NBXPLORER_EXPOSERPC: 1
      NBXPLORER_NOAUTH: 1
    depends_on:
      - bitcoind
      - postgres

volumes:
  regtest_pgdata:
  regtest_bitcoin:
