services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    ports:
      - "49372:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - regtest_nigiri_pgdata:/var/lib/postgresql/data

  nbxplorer:
    image: nicolasdorier/nbxplorer:2.5.29
    restart: unless-stopped
    network_mode: host
    environment:
      NBXPLORER_NETWORK: regtest
      NBXPLORER_CHAINS: "btc"
      NBXPLORER_BTCRPCURL: http://127.0.0.1:18443/
      NBXPLORER_BTCNODEENDPOINT: 127.0.0.1:18444
      NBXPLORER_BTCRPCUSER: admin1
      NBXPLORER_BTCRPCPASSWORD: "123"
      NBXPLORER_BIND: 0.0.0.0:42838
      NBXPLORER_MINGAPSIZE: 5
      NBXPLORER_MAXGAPSIZE: 10
      NBXPLORER_VERBOSE: 1
      NBXPLORER_POSTGRES: User ID=postgres;Include Error Detail=true;Host=127.0.0.1;Port=49372;Database=nbxplorer
      NBXPLORER_EXPOSERPC: 1
      NBXPLORER_NOAUTH: 1

volumes:
  regtest_nigiri_pgdata:
