// <auto-generated />
using System;
using BTCPayServer.LendaSwap.Plugins.Swap.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BTCPayServer.LendaSwap.Plugins.Swap.Data.Migrations
{
    [DbContext(typeof(PluginDbContext))]
    [Migration("20260206100000_AddTokenFields")]
    partial class AddTokenFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("BTCPayServer.LendaSwap.Plugins.Swap")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BTCPayServer.LendaSwap.Plugins.Swap.Data.LendaSwapSetting", b =>
                {
                    b.Property<string>("StoreId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Setting")
                        .HasColumnType("text");

                    b.HasKey("StoreId");

                    b.ToTable("LendaSwapSettings", "BTCPayServer.LendaSwap.Plugins.Swap");
                });

            modelBuilder.Entity("BTCPayServer.LendaSwap.Plugins.Swap.Data.SwapRecord", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<long>("AmountSats")
                        .HasColumnType("bigint");

                    b.Property<string>("ClaimDestination")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("GelatoTaskId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long?>("HtlcExpiryBlock")
                        .HasColumnType("bigint");

                    b.Property<string>("LendaSwapId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PaymentAddress")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("PaymentHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PreimageEncrypted")
                        .HasColumnType("text");

                    b.Property<string>("SourceToken")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StoreId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("SwapType")
                        .HasColumnType("integer");

                    b.Property<string>("TargetHtlcAddress")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("TargetToken")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LendaSwapId");

                    b.HasIndex("Status");

                    b.HasIndex("StoreId");

                    b.ToTable("SwapRecords", "BTCPayServer.LendaSwap.Plugins.Swap");
                });
#pragma warning restore 612, 618
        }
    }
}
